### ISSUE TITLE
About compiling error.

### ISSUE THREAD

**Issue by XunshanMan** [kl456123/AnnotationTools#1]
Hi, 
I'm finding a 3d annotation tool to annotate 3d bounding boxes for those objects in TUM RGBD dataset like this:
![screenshot-1571819092](https://user-images.githubusercontent.com/13925978/67378051-36e14a80-f5b9-11e9-8f22-f745edfc4b0b.png)

I'm wondering if your tool is available. So I downloaded and tried, however error occurs:

```
[  3%] Building CXX object CMakeFiles/AreaPicking.dir/Pickers/AreaPicking.cxx.o
/home/jhz/workspace/projects/dataset_tools/AnnotationTools/Pickers/AreaPicking.cxx:6:28: fatal error: vtkNamedColors.h: No such file or directory
compilation terminated.
CMakeFiles/AreaPicking.dir/build.make:62: recipe for target 'CMakeFiles/AreaPicking.dir/Pickers/AreaPicking.cxx.o' failed
make[2]: *** [CMakeFiles/AreaPicking.dir/Pickers/AreaPicking.cxx.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/AreaPicking.dir/all' failed
make[1]: *** [CMakeFiles/AreaPicking.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

```

I'm wondering what version of vtk are you using?
If it's possible, could you list all your dependency?

Thanks for you.

Best regard,

**Comment by kl456123** [comment]
it says that vtkNamedColors.h: No such file or directory.
it often appears in /usr/local/include/vtk-8.2/vtkNamedColors.h
you can use `locate vtkNamedColors` to check it.

**Comment by XunshanMan** [comment]
> it says that vtkNamedColors.h: No such file or directory.
> it often appears in /usr/local/include/vtk-8.2/vtkNamedColors.h
> you can use `locate vtkNamedColors` to check it.

Thanks for your response.
I used to use VTK 5.x which doesn't have the file vtkNamedColors.h
The file shows since VTK 6.x.
Just note for those who use lower version of VTK.

Best regard,
